### ISSUE TITLE
Explicit option flow config_entry deprecated

### ISSUE THREAD

**Issue by tomlut** [bremor/bureau_of_meteorology#244]
When setting up a new instance of the integration I get this warning:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 16:03:58 (1 occurrences)
Last logged: 16:03:58

Detected that custom integration 'bureau_of_meteorology' sets option flow config_entry explicitly, which is deprecated at custom_components/bureau_of_meteorology/config_flow.py, line 275: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/bremor/bureau_of_meteorology/issues

Core 2025.2.0b7
Supervisor 2025.01.2
Operating System 14.2
Frontend 20250131.0

**Comment by systemtester** [comment]
#250

**Comment by Makin-Things** [comment]
Hi @systemtester thank for the PR, I applied it and created a pre-release 1.3.4, but after updating to that release I can't reconfigure an existing setup. I get an error when I hit the Configure button 'Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble'.
Are yo u able to take a look at why this is so.

Cheers
Simon

**Comment by systemtester** [comment]
Apologies.  New PR #251 with the init argument removed.  Tested and working on the pre-release 1.3.4 version.

**Comment by Makin-Things** [comment]
This should be fixed in 1.3.4, thanks to @systemtester

**Comment by tomlut** [comment]
Thanks Folks.

**Comment by tomlut** [comment]
Unfortunately not fixed. v1.3.4 when pressing the configure button:
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
First occurred: 10:50:05 (2 occurrences)
Last logged: 10:50:26

Error handling request from 127.0.0.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 272, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 76, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 83, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 305, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3510, in async_create_flow
    return handler.async_get_options_flow(entry)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/config/custom_components/bureau_of_meteorology/config_flow.py", line 42, in async_get_options_flow
    return BomOptionsFlow(config_entry)
  File "/config/custom_components/bureau_of_meteorology/config_flow.py", line 275, in __init__
    super().__init__(config_entry)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by systemtester** [comment]
Not at my home PC to check the integration but that stacktrace is the same as the pre-release 1.3.4.  The hint is below.  The 2nd commit removed the config_entry from the init

`File "/config/custom_components/bureau_of_meteorology/config_flow.py", line 275, in __init__
    super().__init__(config_entry)`

**Comment by tomlut** [comment]
I just downloaded 1.3.4 again. All good. 👍

I definitely previously downloaded it after Simon made the last comment 🤷‍♂️
